services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/.headscale/config:/etc/headscale
      - headscale-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      - traefik_net
#    labels:
#      traefik.enable: "true"

networks:
  traefik_net:
    external: true
volumes:
  headscale-data: {}
